/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankGUi;

import connection.com.ConnectionDatabase;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FirstPage() {
        initComponents();
         setLocationRelativeTo(null);
         //getContentPane().setBackground(Color.BLUE);
         a.setBackground(new Color(0,0,0,67));
          b.setBackground(new Color(0,0,0,67));
           u.setBackground(new Color(0,0,0,67));
          p.setBackground(new Color(0,0,0,67));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        u = new javax.swing.JTextField();
        p = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        box = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankGUi/bank_asia_logo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -20, 270, 100);

        jTabbedPane1.setBackground(new java.awt.Color(51, 0, 51));
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Adminstrator log in");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(180, -10, 240, 70);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(100, 100, 70, 22);

        u.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(u);
        u.setBounds(220, 100, 160, 30);

        p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(p);
        p.setBounds(220, 160, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(90, 160, 110, 22);

        c1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(51, 51, 0));
        c1.setText("Show Password");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel5.add(c1);
        c1.setBounds(400, 160, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(230, 220, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("create account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(320, 220, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankGUi/wwwww.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 340);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("General Banking ", jPanel1);

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("Account no:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(170, 70, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Password:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(180, 140, 110, 30);

        a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(a);
        a.setBounds(300, 70, 160, 30);

        b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(b);
        b.setBounds(300, 140, 160, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(300, 200, 70, 30);

        box.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        box.setText("Show password");
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        jPanel3.add(box);
        box.setBounds(460, 150, 130, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankGUi/bank.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 340);

        jTabbedPane1.addTab("Online Banking", jPanel3);
        jTabbedPane1.addTab("Human Resouce Management System ", jTabbedPane2);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 110, 600, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankGUi/bank2222.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 620, 480);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Create Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(450, 340, 127, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user=u.getText();
        String password=p.getText();
        
       if((user.length()>0)&&(password.length()>0)){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                ConnectionDatabase cd=new ConnectionDatabase();
                Connection con=cd.doConnect();
               //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasia","root","apcl123456");
               PreparedStatement pstmt=con.prepareStatement("SELECT* FROM user WHERE name=? AND password=?");
               pstmt.setString(1,user);
               pstmt.setString(2,password);
               ResultSet rs=pstmt.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(null,"Successful");
                   //String n=rs.getString(1);
                   //String n=u.getText();
                    //UserForm info=new UserForm();
                    //info.userName(n);
                    //info.setVisible(true);
                    Loading l=new Loading();
                   l.setVisible(true);
                   l.m1();
                    this.dispose();
              
               }else{
                    JOptionPane.showMessageDialog(null,"invalid","Access Denied",JOptionPane.ERROR_MESSAGE);
               }
               
               
               
               
           }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
           }
           
       }else{
           JOptionPane.showMessageDialog(null,"Please Enter password and user name");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        if(c1.isSelected()){
            p.setEchoChar((char) 0);
        }else{
            p.setEchoChar('*');
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         CreateUser beta =new CreateUser();
        beta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String user=a.getText();
        int r=Integer.parseInt(user);
        String password=b.getText();
        
       if((user.length()>0)&&(password.length()>0)){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                ConnectionDatabase cd=new ConnectionDatabase();
                Connection con=cd.doConnect();
               //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasia","root","apcl123456");
               PreparedStatement pstmt=con.prepareStatement("SELECT* FROM account WHERE account_no=? AND phone=?");
               pstmt.setInt(1,r);
               pstmt.setString(2,password);
               ResultSet rs=pstmt.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(null,"Successful");
                   String n=rs.getString(2);
                   //String n=u.getText();
                    OnlineOne info=new OnlineOne();
                    info.setVisible(true);
                    info.searchName("Welcome "+n);
                    //info.setVisible(true);
                    //Loading l=new Loading();
                   //l.setVisible(true);
                  // l.m1();
                    this.dispose();
              
               }else{
                    JOptionPane.showMessageDialog(null,"invalid","Access Denied",JOptionPane.ERROR_MESSAGE);
               }
               
               
               
               
           }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
           }
           
       }else{
           JOptionPane.showMessageDialog(null,"Please Enter password and user name");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CreateAccount alpha=new CreateAccount();
        alpha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
        if(box.isSelected()){
            b.setEchoChar((char) 0);
        }else{
            b.setEchoChar('*');
        }
    }//GEN-LAST:event_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JPasswordField b;
    private javax.swing.JCheckBox box;
    private javax.swing.JCheckBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPasswordField p;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
